services:
  app:
    container_name: App
    build:
      dockerfile: src/dockerfile
    ports:
      - 5001:8080
    environment:
      ConnectionString: mongodb://root:password@mongo:27017
    networks:
      pokemon:
  
  mongo:
    image: mongo:7
    restart: always
    networks:
      pokemon:
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

networks:
  pokemon:
  